echos/urls.py
from django.urls import path

from . import views

app_name = 'echos'

urlpatterns = [
    path('', views.echo_list, name='echo-list'),
    path('add/', views.add_echo, name='add-echo'),
    path('<echo_id>/', views.echo_detail, name='echo-detail'),
    path('<echo_id>/delete/', views.delete_echo, name='delete-echo'),
    path('<echo_id>/edit/', views.edit_echo, name='edit-echo'),
    path('<echo_id>/waves/', views.echo_wave_list, name='wave-list'),
    path('<echo_id>/waves/add/', views.add_wave, name='add-wave'),
]

main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import include, path

import accounts.views

urlpatterns = [
    path('', lambda _: redirect('echos:echo-list')),
    path('admin/', admin.site.urls),
    path('echos/', include('echos.urls')),
    path('login/', accounts.views.user_login, name='login'),
    path('signup/', accounts.views.user_signup, name='signup'),
    path('logout/', accounts.views.user_logout, name='logout'),
    path('waves/', include('waves.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('', views.profile_list, name='user-list'),
    path('@me/', views.my_profile, name='my-profile'),
    path('<str:username>/', views.user_profile, name='user-profile'),
    path('<str:username>/echos/', views.user_echo_profile, name='user-echo-profile'),
    path('<str:username>/edit/', views.edit_profile, name='edit-profile'),
]

echos/models.py
from django.conf import settings
from django.db import models

# Create your models here.


class Echo(models.Model):
    content = models.TextField(max_length=5000)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='echos'
    )

    class Meta:
        ordering = [
            'created_at',
        ]

echos/forms.py
from django import forms
from .models import Echo



class AddEchoForm(forms.ModelForm):
    class Meta:
        model = Echo
        fields = ('content',)

class EditEchoForm(forms.ModelForm):
    class Meta:
        model = Echo
        fields = ('content',)

echos/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden
from django.shortcuts import redirect, render

from waves.forms import AddWaveForm

from .forms import AddEchoForm, EditEchoForm
from .models import Echo

# Create your views here.
forbidden_msg = 'No tienes permiso para acceder a esta página.'

@login_required
def echo_list(request):
    echos = Echo.objects.all().order_by('-created_at')
    return render(request, 'echos/echo_list.html', dict(echos=echos))


@login_required
def add_echo(request):
    if request.method == 'POST':
        if (form := AddEchoForm(request.POST)).is_valid():
            echo = form.save(commit=False)
            echo.user = request.user
            form.save()
            return redirect('echos:echo-list')
    else:
        form = AddEchoForm()
    return render(request, 'echos/add_echo.html', dict(form=form))


@login_required
def edit_echo(request, echo_id: str):
    echo = Echo.objects.get(id=echo_id)
    if request.user != echo.user:
        return HttpResponseForbidden(forbidden_msg)

    if request.method == 'POST':
        if (form := EditEchoForm(request.POST, instance=echo)).is_valid():
            echo = form.save(commit=False)
            echo.user = request.user
            echo.save()
            return redirect('echos:echo-detail', echo.pk)
    else:
        form = EditEchoForm(instance=echo)

    return render(request, 'echos/edit_echo.html', dict(echo=echo, form=form))



@login_required
def delete_echo(request, echo_id):
    echo = Echo.objects.get(id=echo_id)
    if request.user != echo.user:
        return HttpResponseForbidden(forbidden_msg)
    echo.delete()
    return render(request, 'echos/delete_echo.html', dict(echo=echo))


@login_required
def echo_detail(request, echo_id):
    echo = Echo.objects.get(id=echo_id)
    waves = echo.waves.all()[:5]
    return render(request, 'echos/echo_detail.html', dict(echo=echo, waves=waves))


@login_required
def add_wave(request, echo_id):
    if request.method == 'POST':
        if (form := AddWaveForm(request.POST)).is_valid():
            wave = form.save(commit=False)
            wave.user = request.user
            wave.echo = Echo.objects.get(id=echo_id)
            form.save()
            return redirect('echos:echo-detail', echo_id)
    else:
        form = AddWaveForm()
    return render(request, 'waves/add_wave.html', dict(form=form))


@login_required
def echo_wave_list(request, echo_id):
    echo = Echo.objects.get(id=echo_id)
    waves = echo.waves.all().order_by('-created_at')
    return render(request, 'echos/echo_detail.html', dict(echo=echo, waves=waves))

echos/templates/echos/add_echo.html
{% extends "base.html" %}

{% block body %}
<form method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Guardar">
</form>
<a href="{% url "echos:echo-list" %}">Volver a echo-list</a>
{% endblock body %}

echos/templates/echos/delete_echo.html
{% extends "base.html" %}
{% block body %}
El echo ha sido eliminado correctamente
<a href="{% url "echos:echo-list" %}">volver a echo-list</a>
{% endblock body %}

echos/templates/echos/echo_detail.html
{% extends "base.html" %}
{% block body %}
user: {{echo.user}}<br>
content: {{echo.content}}<br><br><br>
{% for wave in waves %}
<div>{{wave.user}}:{{wave.content}}</div>
{% endfor %}
<a href="{% url "echos:echo-list" %}">Volver a echo-list</a><br>
{% if waves.count >= 5 %}
<a href="{% url "echos:wave-list" echo.pk %}">mostrar todos los waves</a><br>
{% endif %}
<a href="{% url "echos:add-wave" echo.pk %}">Publicar wave</a><br>
{% if echo.user == user %}
<a href="{% url "echos:edit-echo" echo.pk %}">Editar echo</a>
<a href="{% url "echos:delete-echo" echo.pk %}">eliminar echo</a>
{% endif %}
{% endblock body %}

echos/templates/echos/echo_list.html
{% extends "base.html" %}

{% block title %}Título{% endblock title %}
{% block body %}
{% if user.is_authenticated %}
<p>hola {{ user }}, haz click aquí para <a href="{% url "echos:add-echo" %}">crear un nuevo Echo </a>|<a href="{% url 'logout' %}"> Logout</a></p>
<a href="{% url "users:user-list" %}">Ver usuarios</a>
{% else %}
<p><a href="{% url "login" %}">Inicia sesión</a> para crear un nuevo Echo | ¿No tienes cuenta? <a href="{% url 'signup' %}">Create una</a></p>
{% endif %}
<div class="echos">
  {% for echo in echos %}
  <a class="text-decoration-none primary text-primary-emphasis" href="{% url "echos:echo-detail" echo.pk %}">
    <div class="echo border">
      {{echo.user}}, {{echo.created_at}}
      <p>{{echo.content|truncatewords:20}}
      </p>
    </div>
  </a>
</div>
{% endfor %}
<a href="{% url "users:user-profile" user %}">Ver mi perfil</a>
{% endblock body %}

echos/templates/echos/edit_echo.html
{% extends "base.html" %}
{% block body %}

<form method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Guardar">
</form>
{% endblock body %}