main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import include, path

import accounts.views

urlpatterns = [
    path('', lambda _: redirect('echos:echo-list')),
    path('admin/', admin.site.urls),
    path('echos/', include('echos.urls')),
    path('login/', accounts.views.user_login, name='login'),
    path('signup/', accounts.views.user_signup, name='signup'),
    path('logout/', accounts.views.user_logout, name='logout'),
    path('waves/', include('waves.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('', views.profile_list, name='user-list'),
    path('@me/', views.my_profile, name='my-profile'),
    path('<str:username>/', views.user_profile, name='user-profile'),
    path('<str:username>/echos/', views.user_echo_profile, name='user-echo-profile'),
    path('<str:username>/edit/', views.edit_profile, name='edit-profile'),
]

users/models.py
from django.conf import settings
from django.db import models


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    avatar = models.ImageField(
        upload_to='avatars/', null=True, blank=True, default='avatars/noavatar.png'
    )
    bio = models.TextField(
        max_length=300, blank=True, null=True, default='Biografía predeterminada.'
    )

    def __str__(self):
        return self.user.username

users/forms.py
from django import forms

from .models import Profile


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('avatar','bio')

users/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponseForbidden
from django.shortcuts import redirect, render

from echos.models import Echo

from .forms import EditProfileForm
from .models import Profile

# Create your views here.

forbidden_msg = 'No tienes permiso para acceder a esta página.'


@login_required
def profile_list(request):
    users = User.objects.all()
    return render(request, 'users/profile_list.html', dict(users=users))


@login_required
def user_profile(request, username):
    detailed_user = User.objects.get(username=username)
    echos = detailed_user.echos.all().order_by('-created_at')[:5]
    return render(request, 'users/user_profile.html', dict(detailed_user=detailed_user, echos=echos))

@login_required
def my_profile(request):
    return redirect('users:user-profile', request.user)



@login_required
def user_echo_profile(request, username):
    detailed_user = User.objects.get(username=username)
    echos = detailed_user.echos.all().order_by('-created_at')
    return render(request, 'users/user_profile.html', dict(detailed_user=detailed_user, echos=echos))


@login_required
def edit_profile(request, username):
    user = User.objects.get(username=username)
    profile = Profile.objects.get(user=user)
    if request.user != profile.user:
        return HttpResponseForbidden(forbidden_msg)

    if request.method == 'POST':
        if (form := EditProfileForm(request.POST, request.FILES, instance=profile)).is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()
            return redirect('users:user-profile', user)
    else:
        form = EditProfileForm(instance=profile)

    return render(request, 'users/edit_profile.html', dict(profile=profile, form=form))

users/templates/users/edit_profile.html
{% extends "base.html" %}
{% block body %}

<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Guardar">
</form>
{% endblock body %}

users/templates/users/profile_list.html
{% extends "base.html" %}
{% block body %}
{% for user in users %}
<a href={% url "users:user-profile" user.username %}>{{user.username}}</a><br>
{% endfor %}
<a href="{% url "echos:echo-list" %}">Volver a Echo list</a>
{% endblock body %}

users/templates/users/user_profile.html
{% extends "base.html" %}
{% block body %}
<img src="{{ detailed_user.profile.avatar.url }}" alt="Avatar"><br>
{{detailed_user.first_name}}
{{detailed_user.last_name}}<br>
{{detailed_user}}<br>
{{detailed_user.email}}<br>
{{detailed_user.profile.bio}}<br><br>
{% for echo in echos %}
{{echo.content}}<br>
{% endfor %}
{% if user == detailed_user %}
<a href="{% url "users:edit-profile" detailed_user %}">editar perfil</a>
{% endif %}
<a href="{% url "users:user-list" %}">volver a user-list</a>
<a href="{% url "users:user-echo-profile" detailed_user %}">ver echos</a>

{% endblock body %}